# Generated by Django 5.2.7 on 2025-10-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tool_images/')),
                ('condition', models.CharField(choices=[('good', 'Boa Condição'), ('new', 'Novo'), ('recovered', 'Recuperada'), ('maintenance', 'Em Manutenção')], default='good', max_length=20)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tool')),
            ],
        ),
    ]
