# Generated by Django 5.2.7 on 2025-10-16 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='borrower_name',
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tool',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='available_for_loan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
