# Generated by Django 5.2.7 on 2025-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_loan_borrower_name_loan_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
