# Generated by Django 5.2.7 on 2025-10-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_tool_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='tools/'),
        ),
    ]
