# Generated by Django 5.2.7 on 2025-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='tool_images/'),
        ),
    ]
