# Generated by Django 5.2.7 on 2025-10-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_tool_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='available_for_loan',
        ),
    ]
