# Generated by Django 5.2.7 on 2025-10-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_tool_available_for_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'permissions': [('dashboard', 'Pode ver o Dashboard'), ('manage_tools', 'Pode ver a página Gerenciar Ferramentas'), ('virtual_warehouse', 'Pode ver o Armazém Virtual'), ('register_loan', 'Pode ver a página Registrar Empréstimo'), ('active_loans', 'Pode ver a página Empréstimos Ativos'), ('history', 'Pode ver o Histórico de Empréstimos'), ('analytics', 'Pode ver a página de Análise e Relatórios')]},
        ),
    ]
