# Generated by Django 5.2.7 on 2025-11-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_tool_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='borrower',
        ),
        migrations.AddField(
            model_name='loan',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee', verbose_name='Funcionário'),
        ),
    ]
